// Справочник стран (ОКСМ) для международной EMS-доставки.
// code — числовой код ОКСМ (передаётся на бэкенд как mail-direct для тарифа/заказа Почты).
// Список можно расширять; отсортирован по названию в UI.

export type Country = { code: number; name: string }

export const COUNTRIES: Country[] = [
  { code: 36, name: 'Австралия' },
  { code: 40, name: 'Австрия' },
  { code: 31, name: 'Азербайджан' },
  { code: 8, name: 'Албания' },
  { code: 12, name: 'Алжир' },
  { code: 32, name: 'Аргентина' },
  { code: 51, name: 'Армения' },
  { code: 50, name: 'Бангладеш' },
  { code: 48, name: 'Бахрейн' },
  { code: 112, name: 'Беларусь' },
  { code: 56, name: 'Бельгия' },
  { code: 100, name: 'Болгария' },
  { code: 68, name: 'Боливия' },
  { code: 76, name: 'Бразилия' },
  { code: 826, name: 'Великобритания' },
  { code: 348, name: 'Венгрия' },
  { code: 704, name: 'Вьетнам' },
  { code: 276, name: 'Германия' },
  { code: 344, name: 'Гонконг' },
  { code: 300, name: 'Греция' },
  { code: 268, name: 'Грузия' },
  { code: 208, name: 'Дания' },
  { code: 818, name: 'Египет' },
  { code: 376, name: 'Израиль' },
  { code: 356, name: 'Индия' },
  { code: 360, name: 'Индонезия' },
  { code: 400, name: 'Иордания' },
  { code: 364, name: 'Иран' },
  { code: 372, name: 'Ирландия' },
  { code: 352, name: 'Исландия' },
  { code: 724, name: 'Испания' },
  { code: 380, name: 'Италия' },
  { code: 398, name: 'Казахстан' },
  { code: 124, name: 'Канада' },
  { code: 634, name: 'Катар' },
  { code: 404, name: 'Кения' },
  { code: 196, name: 'Кипр' },
  { code: 417, name: 'Киргизия' },
  { code: 156, name: 'Китай' },
  { code: 170, name: 'Колумбия' },
  { code: 410, name: 'Корея (Республика)' },
  { code: 192, name: 'Куба' },
  { code: 414, name: 'Кувейт' },
  { code: 428, name: 'Латвия' },
  { code: 422, name: 'Ливан' },
  { code: 440, name: 'Литва' },
  { code: 442, name: 'Люксембург' },
  { code: 458, name: 'Малайзия' },
  { code: 470, name: 'Мальта' },
  { code: 504, name: 'Марокко' },
  { code: 484, name: 'Мексика' },
  { code: 498, name: 'Молдова' },
  { code: 496, name: 'Монголия' },
  { code: 524, name: 'Непал' },
  { code: 528, name: 'Нидерланды' },
  { code: 554, name: 'Новая Зеландия' },
  { code: 578, name: 'Норвегия' },
  { code: 784, name: 'ОАЭ' },
  { code: 512, name: 'Оман' },
  { code: 586, name: 'Пакистан' },
  { code: 604, name: 'Перу' },
  { code: 616, name: 'Польша' },
  { code: 620, name: 'Португалия' },
  { code: 642, name: 'Румыния' },
  { code: 682, name: 'Саудовская Аравия' },
  { code: 807, name: 'Северная Македония' },
  { code: 688, name: 'Сербия' },
  { code: 702, name: 'Сингапур' },
  { code: 703, name: 'Словакия' },
  { code: 705, name: 'Словения' },
  { code: 840, name: 'США' },
  { code: 762, name: 'Таджикистан' },
  { code: 764, name: 'Таиланд' },
  { code: 788, name: 'Тунис' },
  { code: 795, name: 'Туркмения' },
  { code: 792, name: 'Турция' },
  { code: 860, name: 'Узбекистан' },
  { code: 804, name: 'Украина' },
  { code: 608, name: 'Филиппины' },
  { code: 246, name: 'Финляндия' },
  { code: 250, name: 'Франция' },
  { code: 191, name: 'Хорватия' },
  { code: 499, name: 'Черногория' },
  { code: 203, name: 'Чехия' },
  { code: 152, name: 'Чили' },
  { code: 756, name: 'Швейцария' },
  { code: 752, name: 'Швеция' },
  { code: 144, name: 'Шри-Ланка' },
  { code: 218, name: 'Эквадор' },
  { code: 233, name: 'Эстония' },
  { code: 710, name: 'ЮАР' },
  { code: 392, name: 'Япония' },
].sort((a, b) => a.name.localeCompare(b.name, 'ru'))
